/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS1Module"
 * 	found in "PKCS1.asn1"
 * 	`asn1c -S ./skeletons -fwide-types -no-gen-OER -no-gen-UPER -no-gen-APER`
 */

#include "OtherPrimeInfo.h"

asn_TYPE_member_t asn_MBR_OtherPrimeInfo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct OtherPrimeInfo, prime),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"prime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OtherPrimeInfo, exponent),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"exponent"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct OtherPrimeInfo, coefficient),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"coefficient"
		},
};
static const ber_tlv_tag_t asn_DEF_OtherPrimeInfo_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_OtherPrimeInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 2 }, /* prime */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 1 }, /* exponent */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, -2, 0 } /* coefficient */
};
asn_SEQUENCE_specifics_t asn_SPC_OtherPrimeInfo_specs_1 = {
	sizeof(struct OtherPrimeInfo),
	offsetof(struct OtherPrimeInfo, _asn_ctx),
	asn_MAP_OtherPrimeInfo_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_OtherPrimeInfo = {
	"OtherPrimeInfo",
	"OtherPrimeInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_OtherPrimeInfo_tags_1,
	sizeof(asn_DEF_OtherPrimeInfo_tags_1)
		/sizeof(asn_DEF_OtherPrimeInfo_tags_1[0]), /* 1 */
	asn_DEF_OtherPrimeInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_OtherPrimeInfo_tags_1)
		/sizeof(asn_DEF_OtherPrimeInfo_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_OtherPrimeInfo_1,
	3,	/* Elements count */
	&asn_SPC_OtherPrimeInfo_specs_1	/* Additional specs */
};

