/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_SubjectPublicKeyInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_ECParameters;
extern struct asn_TYPE_descriptor_s asn_DEF_RSAPublicKey;
extern struct asn_TYPE_descriptor_s asn_DEF_RSAPrivateKey;
extern struct asn_TYPE_descriptor_s asn_DEF_EXTERNAL;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module X509PKIXModule in PKIX.asn1 */
	&asn_DEF_SubjectPublicKeyInfo,	
	&asn_DEF_ECParameters,	
	/* From module PKCS1Module in PKCS1.asn1 */
	&asn_DEF_RSAPublicKey,	
	&asn_DEF_RSAPrivateKey,	
	/* From module ASN1C-UsefulInformationObjectClasses in ./standard-modules/ASN1C-UsefulInformationObjectClasses.asn1 */
	&asn_DEF_EXTERNAL,	
	0
};

