/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKCS1Module"
 * 	found in "PKCS1.asn1"
 * 	`asn1c -S ./skeletons -fwide-types -no-gen-OER -no-gen-UPER -no-gen-APER`
 */

#include "RSAPublicKey.h"

static asn_TYPE_member_t asn_MBR_RSAPublicKey_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RSAPublicKey, modulus),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"modulus"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RSAPublicKey, publicExponent),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_INTEGER,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"publicExponent"
		},
};
static const ber_tlv_tag_t asn_DEF_RSAPublicKey_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RSAPublicKey_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* modulus */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 } /* publicExponent */
};
static asn_SEQUENCE_specifics_t asn_SPC_RSAPublicKey_specs_1 = {
	sizeof(struct RSAPublicKey),
	offsetof(struct RSAPublicKey, _asn_ctx),
	asn_MAP_RSAPublicKey_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RSAPublicKey = {
	"RSAPublicKey",
	"RSAPublicKey",
	&asn_OP_SEQUENCE,
	asn_DEF_RSAPublicKey_tags_1,
	sizeof(asn_DEF_RSAPublicKey_tags_1)
		/sizeof(asn_DEF_RSAPublicKey_tags_1[0]), /* 1 */
	asn_DEF_RSAPublicKey_tags_1,	/* Same as above */
	sizeof(asn_DEF_RSAPublicKey_tags_1)
		/sizeof(asn_DEF_RSAPublicKey_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RSAPublicKey_1,
	2,	/* Elements count */
	&asn_SPC_RSAPublicKey_specs_1	/* Additional specs */
};

